---
title: "Untitled"
author: "benjamini mpinga"
date: "2023-02-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

***This principles are some of the basic laws,they are older than 600 years ago.these laws are world wide recognised.are the fundamental rights to everyone and every situation.***
<!--more-->
**Actio Personalis Mortiur Corn Persona**:A parson right of action dies with a parson.

**Actus Nonfacit Reum Nisimens Sit Rea:**A conviction of a crime requires proof of a guilt mind/no criminal conviction untill mind is guilt.

**Audi Alterm Parterm**:Justice must heard both/other side.

**Causa Proxima Et Non Renota Spectatur**:The immediete not the remote cause is to be considered.

**Caveat Emptor:**Let the buyer be aware/without consideration no action arise.

**Deminimus Non Curat Lex**The law does not concern itself with trials.

**Deligatus Non Post Deligare**A deligate can not deligate.

**Ex NudoPacto Non Oritur Actio**An agreement without cosidaration does notarise.

**Exturpi Caus Non Artur Actio:**A cort/a law suit should not assist unlawfull ellegetions.

**Ignorantia Facit/Juris Non Excusat:**Ignorancy of law is not an excuse.

**Lex Non Cogit Ad Imposibilia:**A law can not compell one to do what he can not possibly do.

**Nasciturus Projam Nato Habetur:**The unborn is deemd to have been born to the extend.

**Nemo Debt Esse Judex In Propria:**No one ought to be judge in his own cause.

**Nemo Det Vexar Pro Uno Et Eadem Causa:**No one should vexed twise/over for the same cause.

**Nemo Det Quad On Habet:**No one give what they do not have.

**Nemo Temetur Scipsum Accusare:**No one is bound to incriminate/accuse him self.

**Novus Actus Intervenious:**


**Pendente Lit Nihil Innoveture:**During litigation northing shall be changed/introduced.

**Qui Facit Peralium Facit Per Se:**He who act through another parson does the act himself.

**Res Ipsa Loquitur:**Things speak for themselves.

**Respondent Superior:**Master liable.

**Solus Populi Supreme Lex:**A wellfare of the people shall be suprime law.

**Ubi Jus Ubi Remedium:**For every wrong act the law provide remidy.

**Volent Non Fit Injuria:**To one who is willing no harm is done.



**Related Posts:**:

